config/routes.rb
Rails.application.routes.draw do

  get 'new'    => 'heatmaps#new'
  get 'about'  => 'frontpages#about'
  get 'latest' => 'frontpages#latest'
  post '/main' => 'frontpages#main'
  get 'main'   => 'frontpages#main'
  get 'contact'=> 'frontpages#contact'
  get 'contribute' => 'frontpages#contribute'
  get 'index' => 'public#index'
  get 'past' => 'frontpages#past'

     resources :frontpages

end

app/models/example_user.rb
class User
	attr_accessor :name , :email

	def initialize(attributes = {})
		@name = attributes[:name]
		@email = attributes[:email]
	end
	def formatted_email
		"#{@name} <#{@email}>"
	end

end

app/models/heatmap.rb
class Heatmap < ActiveRecord::Base
	validates :timestamp, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frontpages_controller.rb
require 'nokogiri'
require 'rmagick'
require 'open-uri'
class FrontpagesController < ApplicationController
	
	def new

	end
	def index
	end

	def show

	end

	def create
	end

	def contribute
	end

	def main
		@input = params[:input]
		flash[:notice] = "#{@input}"
		



	end

	def edit
	end

	def destroy
	end

	def update
	end

	def about
	end

	def latest

		weather_link = 'http://www.weather.gov.sg/weather-rain-area-50km/'
		html = Nokogiri::HTML(open(weather_link))
		time_text = html.css('ul.list-unstyled').css('li').map { |e|  e['id']}.compact

		@latestTime = time_text[-1]
		time = Time.parse(@latestTime)
  		year = time.year
  		month = time.strftime("%m")
  		day = time.strftime("%d")
  		hour = time.strftime("%H")
  		min = time.strftime("%M")
  		@image_path = "http://www.weather.gov.sg/files/rainarea/50km/v2/dpsri_70km_#{year}#{month}#{day}#{hour}#{min}0000dBR.dpsri.png"
  		@heatmap_name = @image_path.split("v2/")[1]

  		open(@image_path) { |f|
  			File.open("./app/assets/images/temp.png", "wb") do |file|
  				file.puts f.read
  			end

  		}

  		heatmap ="./app/assets/images/temp.png"

  		map_heatmap = Magick::Image.read(heatmap).first
  		scale_heatmap = map_heatmap.adaptive_resize(853, 479)

  		base = Magick::Image.read("./app/assets/images/base-853.png").first
  		base.composite(scale_heatmap, 0, 0, Magick::OverCompositeOp).write("./app/assets/images/overlay.png")

		
		
	end

	def contact
	end

	def past
	end


end

app/controllers/heatmaps_controller.rb
class HeatmapsController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frontpages_helper.rb
module FrontpagesHelper

end

app/helpers/heatmaps_helper.rb
module HeatmapsHelper
end

app/views/frontpages/about.erb
<h1>About us</h1>

<h4>Nature of problem we hope to address:</h4>

<p style="font-size: 14px">Currently, weather.gov.sg provides a 2 hours forecasting for areas within Singapore. They also provide current weather conditions constantly at 5 minutes intervals through heatmaps. The 2 hours forcast is displayed over general categories of areas in Singapore, which may not be precise for commuters who wish to plan their journey without worrying about the rain. Furthermore, travelling in Singapore often takes less than an hour, thus a 2 hours prediction may not be relevant to most commuters.<br /></p>

<h4>What we hope to achieve:</h4>

<p style="font-size: 14px">Clear Sky hopes to solve this problem using the 5 minutes interval heatmaps to provide a more meaningful/easy to access data for commuters in Singapore.</p>

app/views/frontpages/contact.erb
<p> you can contact us here </p>

app/views/frontpages/contribute.erb
<h1>Contribute to us!</h1>

<h4>For anyone who wants to check out our code</h4>

<a href ="https://github.com/ytbryan/clear_sky/ ">Clear Sky Github page</a>

<h4>Anyone who is free to contribute and improve our code as well</h4>

<a href ="https://github.com/ytbryan/clear_sky/pull/new/master">Send us a pull request!</a>

<h4>List of contributor for this project</h4>

<a href = "https://github.com/ytbryan/clear_sky/graphs/contributors">Contributers</a>

app/views/frontpages/index.html.erb
<p> index page </p>
<ul class="nav navbar-nav navbar-right">
<li><%= link_to "Main", main_path %></li>
<li><%= link_to "Latest Heatmap", latest_path %></li>
<li><%= link_to "about", about_path%></li>

<p> <%=notice %></p>

app/views/frontpages/latest.erb
<h1>Current weather</h1>

<h6>updated at <%=@latestTime %> (Note: If there is no hue on the map, there is currently no rain in Singapore)</h6>

<div id="map" data-heatmap="<%=@image_path %>"></div>

<div id="display_info">
	<div id="scale">
		<p>Rain Intensity:</p>
		<img src="/assets/rain-intensity.jpg" />
	</div>

	<div id="display_toggle">
		<input type="checkbox" name="toggle" id="route_toggle" checked="checked">
		<label for="route_toggle">Route</label>

		<input type="checkbox" name="toggle" id="heatmap_toggle" checked="checked">
		<label for="heatmap_toggle">Heatmap</label>
	</div>
</div>

<div id="controls">
	<p>Search a location or get directions:</p>
	
	<div id="mode-selector">
	  <input type="radio" name="type" id="changemode-walking" checked="checked">
	  <label for="changemode-walking">Walking</label>

	  <input type="radio" name="type" id="changemode-transit">
	  <label for="changemode-transit">Transit</label>

	  <input type="radio" name="type" id="changemode-driving">
	  <label for="changemode-driving">Driving</label>
	</div>

	<input id="origin-input" type="text" placeholder="Enter an origin location">

	<input id="destination-input" type="text" placeholder="Enter a destination location">
</div>

<div id="direction_result" class="display"></div>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzs7lxzMPK6S-jX5YB2n7Ff3SdMQ2PJIE&libraries=places&callback=initMap">
</script>

app/views/frontpages/latest.rb.erb
<p>Current weather</p>


<p>updated at <%=@latestTime %></p>
<img alt=@heatmap_name src="/assets/overlay.png" />

app/views/frontpages/main.erb
<p>test view</p>
<%= form_tag do %>
<%= text_field_tag :input %>
<%= submit_tag :search%>

<% end %>

<p> <%=notice %></p>

app/views/frontpages/past.erb
<p> search for past heatmap</p>

app/views/frontpages/show.erb
<p>test view</p>
<%= form_tag do %>
<%= text_field_tag :input %>
<%= submit_tag :search%>

<% end %>

<p> <%=notice %></p>

app/views/heatmaps/new.html.erb
<h1>Heatmaps#new</h1>
<p>Find me in app/views/heatmaps/new.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<a href="https://potato-clear-sky.herokuapp.com/">Clear Sky</a>
</small>

<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contribute ", contribute_path %></li>
<li><%= link_to "Admin", "#path" %></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%= link_to "Clear_sky", index_path, id: "logo" %>

<nav>
<ul class= "nav navbar-nav navbar-right">
<!-- <li><%= link_to "Demo"  ,main_path %> </li> -->
<li><%= link_to "Demo"  , latest_path %> </li>
<!-- <li><%= link_to "Past HeatMap"  , past_path %> </li> -->

</ul>
</nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClearSky</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<div class ='container' %>
<%= yield %>
<%= render 'layouts/footer' %>
</div>
</body>
</html>